//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMSS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEMSS()
        {
            this.tb_Cart = new HashSet<tb_Cart>();
            this.ProductInfo = new HashSet<ProductInfo>();
            this.ProductsAllocatedToOrders = new HashSet<ProductsAllocatedToOrders>();
        }
    
        public int StockId { get; set; }
        public string StockCode { get; set; }
        public string Name_Item { get; set; }
        public Nullable<int> TYPE_ID { get; set; }
        public Nullable<double> COST_PRICE { get; set; }
        public Nullable<int> STOCK_LEVEL { get; set; }
        public Nullable<int> MIN_STOCK_LEVEL { get; set; }
        public Nullable<System.DateTime> PRICE_CHANGE_DATE { get; set; }
        public bool ReorderWhenLow { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string Vendor_Name { get; set; }
        public Nullable<double> Retail_Margin { get; set; }
        public Nullable<double> Trade_Margin { get; set; }
        public int ItemTypeId { get; set; }
        public Nullable<double> Add_Quantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Cart> tb_Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInfo> ProductInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsAllocatedToOrders> ProductsAllocatedToOrders { get; set; }
    }
}
