//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WICKRAMA_STORESEntities : DbContext
    {
        public WICKRAMA_STORESEntities()
            : base("name=WICKRAMA_STORESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ITEM_TYPES_LOOKUP> ITEM_TYPES_LOOKUP { get; set; }
        public virtual DbSet<ITEMS> ITEMS { get; set; }
        public virtual DbSet<ITEMSS> ITEMSSes { get; set; }
        public virtual DbSet<ItemType> ItemTypes { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<MANUFACTURER_LOOKUP> MANUFACTURER_LOOKUP { get; set; }
        public virtual DbSet<ORDER_STATUS_LOOKUP> ORDER_STATUS_LOOKUP { get; set; }
        public virtual DbSet<OrderElementsStatusLookup> OrderElementsStatusLookups { get; set; }
        public virtual DbSet<OrderPayment> OrderPayments { get; set; }
        public virtual DbSet<ORDER> ORDERS { get; set; }
        public virtual DbSet<OrderStatusTypeLookup> OrderStatusTypeLookups { get; set; }
        public virtual DbSet<OrderType> OrderTypes { get; set; }
        public virtual DbSet<PaymentAccountAccountantType> PaymentAccountAccountantTypes { get; set; }
        public virtual DbSet<PaymentAccountHumanType> PaymentAccountHumanTypes { get; set; }
        public virtual DbSet<PaymentAccount> PaymentAccounts { get; set; }
        public virtual DbSet<PaymentCardTransaction> PaymentCardTransactions { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<PaymentMethodType> PaymentMethodTypes { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PaymentsSagePayCardType> PaymentsSagePayCardTypes { get; set; }
        public virtual DbSet<PaymentTerm> PaymentTerms { get; set; }
        public virtual DbSet<PaymentTransfer> PaymentTransfers { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<ProductInfo> ProductInfoes { get; set; }
        public virtual DbSet<ProductLocation> ProductLocations { get; set; }
        public virtual DbSet<ProductsAllocatedToOrder> ProductsAllocatedToOrders { get; set; }
        public virtual DbSet<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<PurchaseStatu> PurchaseStatus { get; set; }
        public virtual DbSet<PurchaseType> PurchaseTypes { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<sale> sales { get; set; }
        public virtual DbSet<sales_order_detail> sales_order_detail { get; set; }
        public virtual DbSet<SUB_ITEM_TYPES_LOOKUP> SUB_ITEM_TYPES_LOOKUP { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaxRate> TaxRates { get; set; }
        public virtual DbSet<tb_Cart> tb_Cart { get; set; }
        public virtual DbSet<tb_Customer> tb_Customer { get; set; }
        public virtual DbSet<tb_Employee> tb_Employee { get; set; }
        public virtual DbSet<tb_PurchaseReturns> tb_PurchaseReturns { get; set; }
        public virtual DbSet<tb_Sales> tb_Sales { get; set; }
        public virtual DbSet<tb_SalesOrder> tb_SalesOrder { get; set; }
        public virtual DbSet<tb_SalesReturns> tb_SalesReturns { get; set; }
        public virtual DbSet<tb_Supplier> tb_Supplier { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
