//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_STATUS_LOOKUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER_STATUS_LOOKUP()
        {
            this.ORDERS = new HashSet<ORDERS>();
        }
    
        public int STATUS_ID { get; set; }
        public string ORDER_STATUS { get; set; }
        public int OrderStatusTypeId { get; set; }
        public bool System { get; set; }
        public bool DefaultType { get; set; }
    
        public virtual OrderStatusTypeLookup OrderStatusTypeLookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERS> ORDERS { get; set; }
    }
}
