//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERS()
        {
            this.tb_Cart = new HashSet<tb_Cart>();
        }
    
        public int ORDER_NO { get; set; }
        public Nullable<int> CUSTOMER_NO { get; set; }
        public Nullable<System.DateTime> DATE_PLACED { get; set; }
        public Nullable<int> STATUS_ID { get; set; }
        public Nullable<bool> PAID { get; set; }
        public string CUSTOMER_REF { get; set; }
        public Nullable<bool> INVOICED { get; set; }
        public Nullable<System.DateTime> DATE_INVOICED { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<System.DateTime> DATE_ORDERED { get; set; }
        public Nullable<System.DateTime> DATE_PAID { get; set; }
        public string PrivateComments { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> DueTime { get; set; }
        public Nullable<bool> Scheduled { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<bool> Recurring { get; set; }
        public Nullable<int> RecurrTimePeriod { get; set; }
        public Nullable<int> RaisedBy { get; set; }
        public Nullable<bool> UseTradeMargins { get; set; }
        public Nullable<bool> InterestFreeCredit { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<System.DateTime> DueDate2 { get; set; }
        public Nullable<System.DateTime> DueTime2 { get; set; }
        public Nullable<decimal> DueDuration2 { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string ExtOrderNo { get; set; }
    
        public virtual ORDER_STATUS_LOOKUP ORDER_STATUS_LOOKUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Cart> tb_Cart { get; set; }
        public virtual OrderTypes OrderTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}
