//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        public int ORDER_NO { get; set; }
        public int CUSTOMER { get; set; }
        public System.DateTime DATE_PLACED { get; set; }
        public int Route { get; set; }
        public Nullable<bool> PAID { get; set; }
        public string Employee { get; set; }
        public Nullable<bool> INVOICED { get; set; }
        public Nullable<System.DateTime> DATE_INVOICED { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<System.DateTime> DATE_ORDERED { get; set; }
        public Nullable<System.DateTime> DATE_PAID { get; set; }
        public string PrivateComments { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> DueTime { get; set; }
        public Nullable<bool> Scheduled { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<bool> Recurring { get; set; }
        public Nullable<int> RecurrTimePeriod { get; set; }
        public Nullable<int> RaisedBy { get; set; }
        public Nullable<bool> UseTradeMargins { get; set; }
        public Nullable<bool> InterestFreeCredit { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<System.DateTime> DueDate2 { get; set; }
        public Nullable<System.DateTime> DueTime2 { get; set; }
        public Nullable<decimal> DueDuration2 { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string ExtOrderNo { get; set; }
    }
}
