//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int PaymentId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int PaymentAccountId { get; set; }
        public string TransactionRef { get; set; }
        public int PaymentMethodId { get; set; }
        public int UserId { get; set; }
        public Nullable<bool> Reconciled { get; set; }
        public Nullable<System.DateTime> ReconciledDate { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public Nullable<int> OurRef { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> MoneyIn { get; set; }
        public Nullable<decimal> MoneyOut { get; set; }
    
        public virtual PaymentAccounts PaymentAccounts { get; set; }
        public virtual PaymentMethods PaymentMethods { get; set; }
        public virtual PaymentTypes PaymentTypes { get; set; }
    }
}
