//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentAccountHumanTypes
    {
        public int AccountHumanTypeId { get; set; }
        public string HumanDescription { get; set; }
        public Nullable<int> AccountantAccountType { get; set; }
        public Nullable<bool> IsPhysicalAccount { get; set; }
        public Nullable<bool> ReadOnly { get; set; }
    
        public virtual PaymentAccountAccountantTypes PaymentAccountAccountantTypes { get; set; }
    }
}
