//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentCardTransaction
    {
        public int CardTransactionId { get; set; }
        public Nullable<int> PaymentGatewayProviderId { get; set; }
        public string PaymentGatewayTransactionRef { get; set; }
        public string Comments { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    }
}
