//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsAllocatedToOrder
    {
        public int Sku { get; set; }
        public int OrderDetailsId { get; set; }
        public int QtyAllocated { get; set; }
    
        public virtual ITEMSS ITEMSS { get; set; }
    }
}
