//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchases()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetails>();
        }
    
        public int PurchaseId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateOrdered { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<System.DateTime> DateInvoiced { get; set; }
        public Nullable<System.DateTime> DateRequired { get; set; }
        public Nullable<System.DateTime> DateExpected { get; set; }
        public Nullable<System.DateTime> DatePaymentDue { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public Nullable<bool> Paid { get; set; }
        public int UserId { get; set; }
        public string Comments { get; set; }
        public Nullable<int> PurchaseStatusId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string SupplierRef { get; set; }
        public string SupplierInvoiceNo { get; set; }
        public Nullable<int> PurchaseTypeId { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public string NotesToSupplier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseDetails> PurchaseDetails { get; set; }
        public virtual PurchaseStatus PurchaseStatus { get; set; }
        public virtual PurchaseTypes PurchaseTypes { get; set; }
        public virtual tb_Supplier tb_Supplier { get; set; }
    }
}
