//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        public int PurchaseDetailsId { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public string Description { get; set; }
        public string OurSku { get; set; }
        public Nullable<int> OurOrderNo { get; set; }
        public string SupplierSku { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> PriceEach { get; set; }
        public Nullable<double> VatRate { get; set; }
        public Nullable<int> VatId { get; set; }
        public Nullable<bool> Received { get; set; }
    
        public virtual Purchase Purchase { get; set; }
    }
}
