//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int sales_id { get; set; }
        public int sales_order_id { get; set; }
        public System.DateTime Delivered_Date { get; set; }
        public decimal Total_Cost { get; set; }
        public Nullable<bool> Paid { get; set; }
    }
}
