//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_ITEM_TYPES_LOOKUP
    {
        public int ID { get; set; }
        public string SUB_TYPE { get; set; }
        public Nullable<int> PARENT_TYPE_ID { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<double> DefaultRetailMargin { get; set; }
        public Nullable<double> DefaultTradeMargin { get; set; }
        public Nullable<int> DefaultLoyaltyPoints { get; set; }
        public Nullable<double> DefaultWeight { get; set; }
        public int CategoryTypeId { get; set; }
    }
}
