//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxRates
    {
        public int TaxId { get; set; }
        public string TaxCode { get; set; }
        public double TaxRate { get; set; }
        public string TaxDescription { get; set; }
        public bool IsDefaultTaxCode { get; set; }
    }
}
